---
title: "Data-Wrangle-and-Analysis"
output: html_document
date: "2022-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(dplyr)
library(readr)
```

```{r read-files}
scores <- read.csv('compas-scores-raw.csv', stringsAsFactors=FALSE) %>%
  mutate(Ethnic_Code_Text = if_else(Ethnic_Code_Text == "African-Am","African-American", Ethnic_Code_Text))
violent <- read_csv('cox-violent-parsed.csv')
fair_ml <- read_csv('propublica_data_for_fairml.csv')
```

```{r sex-score}
sex_score_recidivism <- scores %>%
  filter(DisplayText == "Risk of Recidivism") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

sex_score_violence <- scores %>%
  filter(DisplayText == "Risk of Violence") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

sex_score_fail_appear <- scores %>%
  filter(DisplayText == "Risk of Failure to Appear") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))
```

```{r sex-score-viz}
ggplot(data = sex_score_recidivism) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Recidivism Score")

ggplot(data = sex_score_violence) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Violence")

ggplot(data = sex_score_fail_appear) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Failure to Appear")
```

```{r race-score}
race_score_recidivism <- scores %>%
  filter(DisplayText == "Risk of Recidivism") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

race_score_violence <- scores %>%
  filter(DisplayText == "Risk of Violence") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

race_score_fail_appear <- scores %>%
  filter(DisplayText == "Risk of Failure to Appear") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))
```

``` {r race-score-viz} 
ggplot(race_score, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Recidivism Score", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))

ggplot(race_score_violence, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Violence", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))

ggplot(race_score_fail_appear, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Failure to Appear", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))
```

```{r}
scores1 <- scores %>% 
  filter(MaritalStatus=="Married") %>% 
  select(Person_ID,AssessmentID,Case_ID,MaritalStatus,DecileScore) 
scores2 <- scores %>% 
  filter(MaritalStatus=="Single")
scores3 <- scores %>% 
  filter(MaritalStatus=="Divorced")
scores4 <- scores %>% 
  filter(MaritalStatus=="Significant Other")
scores1.1<- scores %>% 
  filter(MaritalStatus=="Married", Ethnic_Code_Text=="African-American")

nrow(scores1)
```

```{r}
  scores %>% mutate(DecileScore= as.factor(DecileScore)) %>% mutate(DecileScore=as.numeric(DecileScore))
```

```{r}
 mean(scores1$DecileScore) #married
mean(scores2$DecileScore) #single
mean(scores3$DecileScore) #divorced
mean(scores4$DecileScore) #significant other
mean(scores$DecileScore)
mean(scores1.1$DecileScore)
```

```{r}
violent1 <- violent %>% filter(score_text==c("High","Medium","Low")) %>% select(race, sex, age_cat, score_text) %>% group_by(race,sex,age_cat,score_text) %>% summarise(count=n()) 
```
```{r}
ggplot(violent1, aes(x=factor(score_text, level=c('Low', 'Medium','High')),y=count,fill=race)) +geom_bar(stat="identity") + facet_wrap(~factor(age_cat, levels=c('Greater than 45','25 - 45','Less than 25'))) + xlab("risk level of recidivism") 
```

 