---
title: "Data-Wrangle-and-Analysis"
output: html_document
date: "2022-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r imports}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(scales)
library(ggpubr)
library(rpart)
library(rpart.plot)
```

```{r read-files}
scores <- read.csv('compas-scores-raw.csv') %>%
  mutate(Ethnic_Code_Text = if_else(Ethnic_Code_Text == "African-Am","African-American", Ethnic_Code_Text)) %>%
  mutate(Ethnic_Code_Text = if_else(Ethnic_Code_Text == "Oriental","Asian", Ethnic_Code_Text))
violent <- read.csv('cox-violent-parsed.csv')
fair_ml <- read.csv('propublica_data_for_fairml.csv')
```

```{r}
recidivism <- scores %>%
  filter(DisplayText == "Risk of Recidivism") 

violence <- scores %>%
  filter(DisplayText == "Risk of Violence") 

fail_appear <- scores %>%
  filter(DisplayText == "Risk of Failure to Appear")
```

```{r sex-score}
sex_score_recidivism <- scores %>%
  filter(DisplayText == "Risk of Recidivism") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

sex_score_violence <- scores %>%
  filter(DisplayText == "Risk of Violence") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

sex_score_fail_appear <- scores %>%
  filter(DisplayText == "Risk of Failure to Appear") %>%
  group_by(Sex_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))
```

```{r sex-score-viz}
ggplot(data = sex_score_recidivism) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Recidivism Score")

ggplot(data = sex_score_violence) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Violence")

ggplot(data = sex_score_fail_appear) +
  geom_col(aes(x = Sex_Code_Text, y = avg_score)) +
  labs(title = "Risk of Failure to Appear")
```

```{r race-score}
race_score_recidivism <- scores %>%
  filter(DisplayText == "Risk of Recidivism") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

race_score_violence <- scores %>%
  filter(DisplayText == "Risk of Violence") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))

race_score_fail_appear <- scores %>%
  filter(DisplayText == "Risk of Failure to Appear") %>%
  group_by(Ethnic_Code_Text) %>%
  summarize(avg_score = mean(DecileScore))
```

``` {r race-score-viz} 
ggplot(race_score_recidivism, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Recidivism Score", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))

ggplot(race_score_violence, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Violence", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))

ggplot(race_score_fail_appear, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Ethnic_Code_Text)) +
  geom_bar(stat = 'identity') +
  labs(title = "Risk of Failure to Appear", x = "Race", y = "Average Score") +
  scale_x_discrete(guide = guide_axis(n.dodge=2))
```


```{r adi-one-number-story}
total_avg <- mean((race_score_violence %>% filter(Ethnic_Code_Text != "African-American"))$avg_score)

aa_avg <- mean((race_score_violence %>% filter(Ethnic_Code_Text == "African-American"))$avg_score)

aa_avg / total_avg
```

```{r adi-viz}
race_scores_all <- scores %>%
  mutate(`Score Type` = DisplayText) %>%
  group_by(Ethnic_Code_Text, `Score Type`) %>%
  summarize(avg_score = mean(DecileScore))

ggplot(race_scores_all, aes(fill=`Score Type`, y=avg_score, x=reorder(Ethnic_Code_Text, -avg_score))) + 
    geom_bar(position="dodge", stat="identity") +
    labs(title = "COMPAS Risk Score Averages By Race", x = "Race", y = "Average Score (Maximum of 10)") +
    scale_x_discrete(guide = guide_axis(n.dodge=2)) +
    scale_fill_manual(values = c("#2e282a", "#EF3E36", "#17BEBB")) +
    theme_light()
```

```{r finn-viz}
sex_race_score_recidivism <- scores %>%
  group_by(Sex_Code_Text, Ethnic_Code_Text, DisplayText) %>%
  summarize(avg_score = mean(DecileScore))

ggplot(sex_race_score_recidivism, aes(x = reorder(Ethnic_Code_Text, -avg_score), y = avg_score, fill = Sex_Code_Text)) +
  geom_bar(stat = 'identity', position = 'dodge') +
  labs(title = "Risk of Recidivism Score", x = "Race", y = "Average Score", fill = "Sex") +
  theme_minimal()
```

```{r finn-numerical-summaries}
table(scores$Sex_Code_Text)
table(scores$Ethnic_Code_Text)
table(scores$MaritalStatus)
table(scores$DisplayText)
table(scores$DecileScore)
```

```{r}
clean <- scores %>% 
  filter(DecileScore > 0, DecileScore <= 10) %>%
  mutate(color = case_when(DecileScore < 6 ~ "Unlikely",
  (DecileScore >= 6 & DecileScore < 8) ~ "Probable",
  DecileScore >= 8 ~ "Likely")) %>%
  mutate(DecileScore = as.character(DecileScore))

clean$DecileScore = factor(clean$DecileScore, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"))

bar <- ggplot(clean, aes(x = DecileScore, fill = color)) + 
  geom_bar() + 
  scale_fill_manual(values=c("#ED2938", "#FFE733", "#024E1B"))

dense <- ggplot(clean, aes(x = RawScore)) + 
  geom_density()

ggarrange(bar, dense, labels = c("Decile Score Distribution", "Raw Score Distribution"), ncol = 1, nrow = 2)
```

```{r}
clean_recid <- clean %>% filter(DisplayText == "Risk of Recidivism")
clean_violence <- clean %>% filter(DisplayText == "Risk of Violence")
clean_fail_appr <- clean %>% filter(DisplayText == "Risk of Failure to Appear")

bar_recid <- ggplot(clean_recid, aes(x = DecileScore, fill = color)) + 
  geom_bar() + 
  scale_fill_manual(values=c("#ED2938", "#FFE733", "#024E1B")) +
  labs(title = "Recidivism Scores")

bar_violence <- ggplot(clean_violence, aes(x = DecileScore, fill = color)) + 
  geom_bar() + 
  scale_fill_manual(values=c("#ED2938", "#FFE733", "#024E1B")) + 
  labs(title = "Violence Scores") + 
  theme(legend.position = "none")

bar_fail_appr <- ggplot(clean_fail_appr, aes(x = DecileScore, fill = color)) + 
  geom_bar() + 
  scale_fill_manual(values=c("#ED2938", "#FFE733", "#024E1B")) + 
  labs(title = "Failure to Appear Scores") + 
  theme(legend.position = "none")

ggarrange(bar_recid, ggarrange(bar_violence, bar_fail_appr, ncol = 2), nrow = 2, common.legend = TRUE, legend = "bottom")
```

```{r}
ind <- sample(2, nrow(clean_recid), replace = T, prob = c(0.8, 0.2))
recid_train <- clean_recid[ind == 1,] %>% select(Agency_Text, Sex_Code_Text, Ethnic_Code_Text, DateOfBirth, ScaleSet, AssessmentReason, Language, LegalStatus, CustodyStatus, ScoreText)
recid_test <- clean_recid[ind == 2,] %>% select(Agency_Text, Sex_Code_Text, Ethnic_Code_Text, DateOfBirth, ScaleSet, AssessmentReason, Language, LegalStatus, CustodyStatus, ScoreText)

recid_train <- clean_recid[ind == 1,]
recid_test <- clean_recid[ind == 2,]

# tree <- rpart(ScoreText ~., data = recid_train, cp = 0.1)
# rpart.plot(tree)
```


```{r}
# total_ppl = /ncol(scores)

percent_scores <- scores %>%
  group_by(ScoreText) %>%
  summarize(total = n(), DisplayText) %>%
  group_by(DisplayText, ScoreText) %>%
  summarize(total_percent = n()/total) %>%
  filter(ScoreText != "N/A") 

ggplot(percent_scores, aes(x = reorder(ScoreText, -total_percent), y = total_percent, fill = ScoreText)) + 
  geom_col() +
  facet_wrap(~DisplayText) + 
  labs(x = "Risk Score Given", y = "Percent of Population", title = "Distribution of Scores Given By Risk Type") + 
  guides(fill = guide_legend(title = "Score Given"))
```

